/*
 * Generated by MTK SP DrvGen Version 03.13.0 for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Wed May 29 18:40:54 2013
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


